# All other configuration (.yml) files that are in the same "/configurations" folder
# will inherit this base "application.yml" file configuration.

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
name:
  value: bhargav
spring:
  cloud:
    config:
      override-system-properties: false

management:
  tracing:
    sampling:
      probability: 1.0